### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by garyzhubc** [kaskr/adcomp#285]
How should I fixed this when I have TMB already installed in R?

```
> library(TMB)
> ## Optionally:
> ## precompile()
> runExample(all=TRUE)
Running example ar1xar1 

> require(TMB)

> set.seed(123)

> n <- 50 ## Size of problem = n*n

> ## ======================= Simulate separable 2D GMRF 
> ## - With exponential correlation in both directions
> ## - phi1 = 1-lag correlation in 1st .... [TRUNCATED] 

> simgmrf <- function(n1,n2,phi1,phi2){
+   u <- matrix(rnorm(n1*n2),n1,n2)
+   L1 <- t(chol(ar1corr(n1,phi1)))
+   L2 <- t(chol(ar1corr(n2,phi2)))
+  .... [TRUNCATED] 

> ## ======================= Simulate data
> phi1=exp(-1/(.1*n)) ## Correlation range=10% of grid size first dimension

> phi2=exp(-1/(.2*n)) ## Correlation range=20% of grid size second dimension

> eta <- simgmrf(n,n,phi1,phi2)

> N <- rpois(length(eta),exp(eta))

> d <- expand.grid(x=factor(1:n),y=factor(1:n))

> d$N <- N

> ## ======================= Parameterization of phi
> f <- function(x) 2/(1 + exp(-2 * x)) - 1

> invf <- function(y) -0.5 * log(2/(y + 1) - 1)

> ## ======================= Fit model
> dyn.load(dynlib("ar1xar1"))

> obj <- MakeADFun(data=list(N=N),
+                  parameters=list(
+                    eta=matrix(0,n,n),
+                    transf_phi1=invf(0 .... [TRUNCATED] 
Constructing atomic D_lgamma
Constructing atomic ppois
Constructing atomic D_lgamma
Constructing atomic ppois

> runSymbolicAnalysis(obj)
note: tmb_symbolic not installed
NULL

> opt <- nlminb(obj$par, obj$fn, obj$gr)
Constructing atomic D_lgamma
Constructing atomic ppois
Optimizing tape... Done
iter: 1  value: 6885.956 mgc: 20 ustep: 0.4367355 
iter: 2  value: 5343.147 mgc: 642.9732 ustep: 0.6608936 
iter: 3  value: 4927.595 mgc: 232.6645 ustep: 0.8129723 
iter: 4  value: 4832.851 mgc: 81.55753 ustep: 0.9016596 
iter: 5  value: 4817.546 mgc: 25.87213 ustep: 0.9495626 
iter: 6  value: 4816.508 mgc: 6.042968 ustep: 0.9744576 
iter: 7  value: 4816.498 mgc: 0.6025625 ustep: 0.9871475 
iter: 8  value: 4816.498 mgc: 0.007909423 ustep: 0.9935536 
iter: 9  value: 4816.498 mgc: 3.812203e-06 ustep: 0.9967719 
iter: 10  mgc: 1.377157e-09 
iter: 1  mgc: 1.377157e-09 
Matching hessian patterns... Done
outer mgc:  269.3098 
iter: 1  value: 2658.061 mgc: 33.60085 ustep: 1 
iter: 2  value: 2655.567 mgc: 0.7862459 ustep: 1 
iter: 3  value: 2655.566 mgc: 0.01653336 ustep: 1 
iter: 4  value: 2655.566 mgc: 1.825918e-05 ustep: 1 
iter: 5  mgc: 4.603273e-11 
iter: 1  mgc: 4.603273e-11 
outer mgc:  48.17188 
iter: 1  value: 2254.791 mgc: 10.02043 ustep: 1 
iter: 2  value: 2253.397 mgc: 0.3251882 ustep: 1 
iter: 3  value: 2253.396 mgc: 0.005962417 ustep: 1 
iter: 4  value: 2253.396 mgc: 4.151839e-06 ustep: 1 
iter: 5  mgc: 2.363443e-12 
iter: 1  value: 2394.454 mgc: 2.034237 ustep: 1 
iter: 2  value: 2394.454 mgc: 0.01115203 ustep: 1 
iter: 3  value: 2394.454 mgc: 3.050233e-06 ustep: 1 
iter: 4  mgc: 3.406164e-13 
iter: 1  mgc: 3.406164e-13 
outer mgc:  26.75679 
iter: 1  value: 2135.236 mgc: 2.041127 ustep: 1 
iter: 2  value: 2135.234 mgc: 0.01873564 ustep: 1 
iter: 3  value: 2135.234 mgc: 1.184221e-05 ustep: 1 
iter: 4  mgc: 1.792788e-11 
iter: 1  value: 2175.709 mgc: 1.738475 ustep: 1 
iter: 2  value: 2175.709 mgc: 0.008466635 ustep: 1 
iter: 3  value: 2175.709 mgc: 1.725205e-06 ustep: 1 
iter: 4  mgc: 1.012523e-13 
iter: 1  mgc: 1.012523e-13 
outer mgc:  9.217527 
iter: 1  value: 2146.151 mgc: 0.7211679 ustep: 1 
iter: 2  value: 2146.151 mgc: 0.007769844 ustep: 1 
iter: 3  value: 2146.151 mgc: 3.19147e-06 ustep: 1 
iter: 4  mgc: 1.333489e-12 
iter: 1  value: 2132.166 mgc: 0.3271636 ustep: 1 
iter: 2  value: 2132.166 mgc: 0.0003473912 ustep: 1 
iter: 3  mgc: 2.947777e-09 
iter: 1  mgc: 2.947777e-09 
outer mgc:  5.611706 
iter: 1  value: 2081.054 mgc: 0.3786668 ustep: 1 
iter: 2  value: 2081.054 mgc: 0.0005907782 ustep: 1 
iter: 3  value: 2081.054 mgc: 1.037565e-08 ustep: 1 
iter: 4  mgc: 2.753353e-14 
iter: 1  mgc: 2.753353e-14 
outer mgc:  4.475974 
iter: 1  value: 2054.238 mgc: 0.2162679 ustep: 1 
iter: 2  value: 2054.238 mgc: 0.0003656045 ustep: 1 
iter: 3  mgc: 4.192688e-09 
iter: 1  mgc: 4.192688e-09 
outer mgc:  3.215501 
iter: 1  value: 2144.205 mgc: 0.6479573 ustep: 1 
iter: 2  value: 2144.205 mgc: 0.001619812 ustep: 1 
iter: 3  value: 2144.205 mgc: 6.02096e-08 ustep: 1 
iter: 4  mgc: 2.808864e-14 
iter: 1  value: 2060.646 mgc: 0.0500947 ustep: 1 
iter: 2  value: 2060.646 mgc: 1.321175e-05 ustep: 1 
iter: 3  mgc: 4.763301e-12 
iter: 1  mgc: 4.763301e-12 
outer mgc:  1.855526 
iter: 1  value: 2050.217 mgc: 0.0745541 ustep: 1 
iter: 2  value: 2050.217 mgc: 4.397263e-05 ustep: 1 
iter: 3  mgc: 7.73086e-11 
iter: 1  mgc: 7.73086e-11 
outer mgc:  1.65933 
iter: 1  value: 2078.012 mgc: 0.2047107 ustep: 1 
iter: 2  value: 2078.012 mgc: 0.0001406034 ustep: 1 
iter: 3  mgc: 5.04472e-10 
iter: 1  mgc: 5.04472e-10 
outer mgc:  0.8381889 
iter: 1  value: 2065.017 mgc: 0.09893688 ustep: 1 
iter: 2  value: 2065.017 mgc: 3.771526e-05 ustep: 1 
iter: 3  mgc: 3.057465e-11 
iter: 1  mgc: 3.057465e-11 
outer mgc:  0.8112865 
iter: 1  value: 2070.225 mgc: 0.04099468 ustep: 1 
iter: 2  value: 2070.225 mgc: 9.427594e-06 ustep: 1 
iter: 3  mgc: 2.881695e-12 
iter: 1  mgc: 2.881695e-12 
outer mgc:  0.4627224 
iter: 1  value: 2066.774 mgc: 0.02651695 ustep: 1 
iter: 2  value: 2066.774 mgc: 3.076232e-06 ustep: 1 
iter: 3  mgc: 2.078338e-13 
iter: 1  mgc: 2.078338e-13 
outer mgc:  0.1085688 
iter: 1  value: 2069.814 mgc: 0.02243911 ustep: 1 
iter: 2  value: 2069.814 mgc: 1.520155e-06 ustep: 1 
iter: 3  mgc: 8.726353e-14 
iter: 1  value: 2067.94 mgc: 0.008679881 ustep: 1 
iter: 2  value: 2067.94 mgc: 2.464231e-07 ustep: 1 
iter: 3  mgc: 3.455569e-14 
iter: 1  mgc: 3.455569e-14 
outer mgc:  0.005613724 
iter: 1  value: 2067.922 mgc: 0.0001470843 ustep: 1 
iter: 2  mgc: 3.992646e-10 
iter: 1  mgc: 3.992646e-10 
outer mgc:  0.001929325 
iter: 1  mgc: 3.992646e-10 
Building example linreg_parallel 
Note: Using Makevars in /Users/garyzhu/.R/Makevars 
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Users/garyzhu/Library/R/3.5/library/TMB/include -I/Users/garyzhu/Library/R/3.5/library/RcppEigen/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_linreg_parallel  -DTMB_LIB_INIT=R_init_linreg_parallel   -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c linreg_parallel.cpp -o linreg_parallel.o
clang: error: unsupported option '-fopenmp'
make: *** [linreg_parallel.o] Error 1
Error in compile(paste0(name, ".cpp"), ...) : Compilation failed
Timing stopped at: 0.068 0.17 0.3
```

**Comment by MarieAugerMethe** [comment]
Yes, it looks like you have an issue with your installation.

**Comment by JennaVergeynst** [comment]
Same error here, after I updated TMB... I'm working with R version 3.5.0. And on a mac OS X El Capitan 10.11.6 (if that matters).

**Comment by bbolker** [comment]
From the [glmmTMB README file](https://github.com/glmmTMB/glmmTMB/blob/master/README.md):

> if you get errors about unsupported option '-fopenmp'you need to turn off OpenMP compilation by adding the line SHLIB_OPENMP_CFLAGS= to your ~/.R/Makevars file. If you've already done step #1 this file will already exist; use a text editor to add the line above. Otherwise, you need to create it.

AFAICT this happens when you have a CRAN-compiled version of R and are trying to compile TMB locally - the options don't match any more.

**Comment by garyzhubc** [comment]
Changing Makevars works. Here is another post to follow https://github.com/kaskr/adcomp/issues/268.

**Comment by JennaVergeynst** [comment]
Mmh, in my case the problem is not solved by creating this Makevars file. Any other suggestions?
